CREATE TABLE [smp].[User]
(
	[Id] INT NOT NULL IDENTITY(1,1),
	[Email] NVARCHAR(128) NOT NULL,
	[Password] NVARCHAR(128) NOT NULL,
	[FirstName] NVARCHAR(64) NULL,
	[LastName] NVARCHAR(64) NULL,
	[Location] NVARCHAR(64) NULL,
	[IsAdmin] BIT DEFAULT 0 NOT NULL,
	[IsActive] BIT DEFAULT 0 NOT NULL,
	[IsUploader] BIT DEFAULT 0 NOT NULL,
	[ActivationDate] DATETIME DEFAULT NULL,
	CONSTRAINT [PK_UserId] PRIMARY KEY ([Id])
)
